# Generated by Django 3.2.9 on 2021-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='subject',
            field=models.TextField(default='none'),
        ),
    ]
