# Generated by Django 3.2.9 on 2021-12-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_id'),
        ('allBlogs', '0002_allblogs_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
