# Generated by Django 3.2.9 on 2021-12-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211114_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
