# Generated by Django 3.2.9 on 2021-12-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
